all:
	g++ -o RVMTest RVMTest.cpp
	g++ -o ENVTest ENVTest.cpp
	g++ -o ExceptionsTest ExceptionsTest.cpp ../Exceptions.cpp
	g++ -o ProjectTest ProjectTest.cpp ../Project.cpp ../Exceptions.cpp
clean:
	rm -rf RVMTest ENVTest ExceptionsTest ProjectTest
